### ISSUE TITLE
Error loading state dict for the NLI scoring

### ISSUE THREAD

**Issue by oplatek** [wenhuchen/LogicNLG#19]
Hi,
I downloaded the NLI models and I am trying to run them by the command below, but I got the following error.
```
# On GPU machine with visible GPU
$ NLI.py --model bert-base-multilingual-uncased --do_verify --encoding gnn --load_from NLI_models/model_ep4.pt --fp16 --verify_file ../../outputs/SQL_pipeline_V2_llama3_t0_test_LotNLG_LogicNLG_format.json --verify_linking data/test_lm.json
Traceback (most recent call last):
  File "NLI.py", line 371, in <module>
    model.load_state_dict(torch.load(args.load_from))
  File "/lnet/express/work/people/oplatek/SQuirreLtells/nli-acc-score/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GNN:
        Missing key(s) in state_dict: "BASE.embeddings.position_ids". 
```

**Comment by oplatek** [comment]
I thought I correctly had transformers `transformers==2.5.1` installed, but I installed `transformers==4.2.2`. The transformers library's mismatched version caused this error.
